kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-additional-storage-csi-resizer-binding
  labels:
    {{- include "nifcloud-additional-storage-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nifcloud-additional-storage-csi-external-resizer-role
  apiGroup: rbac.authorization.k8s.io
