apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: additional-storage.csi.nifcloud.com
  labels:
    {{- include "nifcloud-additional-storage-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false
