kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-additional-storage-csi-leases-role
  labels:
    {{- include "nifcloud-additional-storage-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
