kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-additional-storage-csi-leases-rolebinding
  labels:
    {{- include "nifcloud-additional-storage-csi-driver.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: nifcloud-additional-storage-csi-leases-role
  apiGroup: rbac.authorization.k8s.io
